server:
  port: 8010
  servlet:
    # 配置应用访问上下文路径
    context-path: /api

spring:
  jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
  application:
    name: intelliStore-co-pic-helper
  servlet:
    multipart:
      max-file-size: 10MB
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelliStore_co_pic_helper
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
  # 空间图片分表
  shardingsphere:
    datasource:
      names: intellistore_co_pic_helper
      intellistore_co_pic_helper:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/intellistore_co_pic_helper
        username: root
        password: root
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: intellistore_co_pic_helper.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.hao_xiao_zi.intellistorecopichelper.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
mybatis-plus:
  global-config:
    enable-sql-runner: true # 开启sql运行器
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1 # 默认逻辑删除值
      logic-not-delete-value: 0 # 默认逻辑未删除值
  #      update-strategy: not_null # 全局忽略null值更新
  configuration:
    # 仅在开发环境启用日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
knife4j:
  enable: true
  openapi:
    title: 智存协图助手官方文档
    description: 智存协图助手
    email: 3425588767@qq.com
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.hao_xiao_zi.intellistorecopichelper.controller
          - com.hao_xiao_zi.intellistorecopichelper.manager
